# Generated by Django 5.2.4 on 2025-07-18 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Patient'), (2, 'Doctor'), (3, 'Admin')], default=3),
        ),
    ]
